language: go

go:
  - "1.15"
before_install:
  - go get github.com/mattn/goveralls
after_success:
  - go test -covermode=count -coverprofile=profile.cov ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci